// core/config.h — the single registry of every tunable constant.
//
// The design rule from the spec is "all constants live in an editable config
// file, none hardcoded in logic". That is enforced structurally rather than by
// discipline: a constant is DECLARED once here with key, description, default
// and range, and read through the registry. Two things then come for free:
//
//   1. data/config.ini round-trips, with descriptions written as comments.
//   2. The Settings screen is GENERATED by walking the registry, so any
//      constant added in a later milestone appears in the UI, with its tooltip
//      and its range and a working "restore defaults", without a line of UI
//      code being written for it.
#pragma once

#include <cstdint>
#include <string>
#include <unordered_map>
#include <vector>

namespace gen {

enum class CfgType : uint8_t { Bool, Int, Float, String };

struct CfgEntry {
    std::string section;      // "world", "sim", "env", ...
    std::string name;         // "size", "batch_target_ms", ...
    std::string key;          // "world.size"
    std::string description;  // shown as tooltip and as an .ini comment
    CfgType     type = CfgType::Float;

    double      value = 0.0;      // Bool/Int/Float live here
    double      defaultValue = 0.0;
    double      minValue = 0.0;
    double      maxValue = 0.0;
    bool        logarithmic = false;  // UI hint for wide ranges

    std::string strValue;
    std::string strDefault;

    bool isNumeric() const { return type != CfgType::String; }
};

class Config {
public:
    static Config& instance();

    // Registration. Calling register* twice with the same key is harmless (the
    // second call is ignored), which keeps static-init order from mattering.
    void registerBool (const char* key, bool  def, const char* desc);
    void registerInt  (const char* key, int64_t def, int64_t lo, int64_t hi,
                       const char* desc, bool logarithmic = false);
    void registerFloat(const char* key, double def, double lo, double hi,
                       const char* desc, bool logarithmic = false);
    void registerString(const char* key, const char* def, const char* desc);

    // Access. Reading an unregistered key is a programming error and returns
    // the supplied fallback rather than throwing, so a stale key in a hand
    // edited .ini cannot take the whole run down.
    bool     getBool  (const char* key, bool fallback = false) const;
    int64_t  getInt   (const char* key, int64_t fallback = 0) const;
    double   getFloat (const char* key, double fallback = 0.0) const;
    float    getF     (const char* key, float fallback = 0.0f) const {
        return static_cast<float>(getFloat(key, static_cast<double>(fallback)));
    }
    const std::string& getString(const char* key) const;

    void setBool  (const char* key, bool v);
    void setInt   (const char* key, int64_t v);
    void setFloat (const char* key, double v);
    void setString(const char* key, const std::string& v);

    bool load(const std::string& path);   // false if the file does not exist
    bool save(const std::string& path) const;

    void restoreDefaults();
    void restoreDefaults(const std::string& section);

    // For the generated Settings UI.
    const std::vector<CfgEntry>& entries() const { return m_entries; }
    std::vector<CfgEntry>&       entriesMutable() { return m_entries; }
    std::vector<std::string>     sections() const;

    const std::string& lastLoadPath() const { return m_lastLoadPath; }
    bool loadedFromFile() const { return m_loadedFromFile; }

    // Resolves a key to its slot once. Public so CfgRef below can use it; the
    // slot is stable for the lifetime of the process because entries are only
    // ever appended, during registerAllSettings().
    int slotOf(const char* key) const { return indexOf(key); }
    double valueAt(int slot) const {
        return (slot >= 0 && slot < static_cast<int>(m_entries.size()))
            ? m_entries[static_cast<size_t>(slot)].value : 0.0;
    }

private:
    Config() = default;
    int indexOf(const char* key) const;
    CfgEntry& add(const char* key, CfgType type, const char* desc);
    static void splitKey(const std::string& key, std::string& section, std::string& name);

    std::vector<CfgEntry>                  m_entries;
    std::unordered_map<std::string, int>   m_index;
    std::string                            m_lastLoadPath;
    bool                                   m_loadedFromFile = false;
};

// Declares every GENESIS constant. Called once at startup, before load().
void registerAllSettings();

inline Config& cfg() { return Config::instance(); }

// A resolved handle to one constant, for use on the per-agent path.
//
// cfg().getF("key") hashes a string and probes a map on every call. That is
// nothing on its own and a great deal inside a loop that runs once per agent per
// tick: at 10,000 agents a single such lookup in the inner loop is 10,000 string
// hashes per tick. This resolves the slot ONCE -- as a function-local static, so
// it happens on first use and never again -- and then reads the live value out of
// the entry.
//
// Reading the value live rather than caching it is the important part: a god-mode
// edit or a Lua config.set must still take effect immediately, so caching the
// NUMBER would silently break rule changes mid-run. Only the lookup is cached.
// Resolution is LAZY, on first read, and that detail is not optional. A CfgRef at
// file scope is constructed during static initialisation, which happens before
// main() calls registerAllSettings() -- so resolving in the constructor found
// nothing, every read returned 0, and a capacity constant of 0 walked off the end
// of an empty vector. Resolving on first use means the first read happens from
// the tick, long after registration.
class CfgRef {
public:
    explicit CfgRef(const char* key) : m_key(key) {}

    float  f() const { return static_cast<float>(cfg().valueAt(slot())); }
    double d() const { return cfg().valueAt(slot()); }
    int    i() const { return static_cast<int>(cfg().valueAt(slot())); }
    bool   b() const { return cfg().valueAt(slot()) != 0.0; }

private:
    int slot() const {
        // Benign to compute more than once if two threads race here: both
        // compute the same value and write the same value, and neither result
        // depends on the other. No lock, therefore no cost on the hot path.
        if (m_slot == kUnresolved) m_slot = cfg().slotOf(m_key);
        return m_slot;
    }

    static constexpr int kUnresolved = -2;   // -1 already means "no such key"
    const char* m_key;
    mutable int m_slot = kUnresolved;
};

}  // namespace gen
